Repository Car-Give/Backend, pull requests merged in 2023-10, with the labels that each got.

#32 [Feat] Elastic Beanstalk을 통한 CI/CD를 위한 설정 파일 추가
  .ebextensions/00-makeFiles.config
  .github/workflows/deploy.yml
  .platform/nginx.conf
  Procfile
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  settings.gradle
  src/main/java/com/example/cargive/global/infra/ElasticBeanstalkHealthCheck.java
Labels: 💻 Infra

#33 [Feat] 누락된 deploy 시점을 추가한다
  .github/workflows/deploy.yml
Labels: 🌏 Deploy

#38 [Feat] RDS 설정을 추가한다
  .github/workflows/deploy.yml
  src/main/resources/application.yml
Labels: 🌏 Deploy, 💻 Infra

#39 [Feat] profile 지정을 위한 build 설정을 추가한다
  .github/workflows/deploy.yml
  build.gradle
Labels: 🌏 Deploy

#42 [Feat] S3를 설정하고 파일 업로드하는 기능을 구현한다
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/com/example/cargive/global/base/BaseResponseStatus.java
  src/main/java/com/example/cargive/global/config/S3Config.java
  src/main/java/com/example/cargive/global/service/S3Service.java
  src/main/resources/application.yml
  src/test/java/com/example/cargive/global/config/S3MockConfig.java
  src/test/java/com/example/cargive/global/service/S3ServiceTest.java
  src/test/resources/application.yml
  src/test/resources/files/test.png
  src/test/resources/files/test.txt
Labels: ✨ Feature, 💻 Infra, ✅ Test

#45 [Fix] yml 환경변수 형식 수정 및 S3 업로드 용량을 제한한다
  src/main/resources/application.yml
Labels: 🐞 BugFix

#46 [Feat] 누락된 의존성 추가 및 yml을 수정한다
  build.gradle
  src/main/resources/application.yml
Labels: ✨ Feature

#43 [Feat] OAuth를 활용한 로그인, 회원 가입을 구현한다
  build.gradle
  src/main/java/com/example/cargive/domain/auth/dto/OAuthAttributes.java
  src/main/java/com/example/cargive/domain/auth/dto/UserProfile.java
  src/main/java/com/example/cargive/domain/auth/service/CustomOAuth2UserService.java
  src/main/java/com/example/cargive/domain/member/entity/Email.java
  src/main/java/com/example/cargive/domain/member/repository/MemberRepository.java
  src/main/java/com/example/cargive/global/config/SecurityConfig.java
  src/test/resources/application.yml
Labels: 📬 API, ✨ Feature

#52 [Fix] mysql 버전 오기를 수정한다
  src/main/resources/application-prod.yml
Labels: 🐞 BugFix

#53 [Fix] dialect mysql 버전을 수정한다
  src/main/resources/application-prod.yml
Labels: 🐞 BugFix

#50 [Feat] Entity 연관 관계 설정, 회원 탈퇴, 정보 수정 기능을 구현하고 테스트 코드를 작성한다
  src/main/java/com/example/cargive/domain/car/entity/Car.java
  src/main/java/com/example/cargive/domain/car/service/CarService.java
  src/main/java/com/example/cargive/domain/favorite/entity/Favorite.java
  src/main/java/com/example/cargive/domain/favorite/service/FavoriteCarService.java
  src/main/java/com/example/cargive/domain/favorite/service/FavoritePkGroupService.java
  src/main/java/com/example/cargive/domain/member/controller/MemberController.java
  src/main/java/com/example/cargive/domain/member/controller/dto/request/MemberRequest.java
  src/main/java/com/example/cargive/domain/member/controller/dto/response/MemberResponse.java
  src/main/java/com/example/cargive/domain/member/entity/Member.java
  src/main/java/com/example/cargive/domain/member/service/MemberService.java
  src/main/java/com/example/cargive/global/base/BaseResponseStatus.java
  src/test/java/com/example/cargive/common/ControllerTest.java
  src/test/java/com/example/cargive/member/controller/MemberControllerTest.java
  src/test/java/com/example/cargive/member/domain/MemberTest.java
  src/test/java/com/example/cargive/member/service/MemberServiceTest.java
Labels: 📬 API, ✨ Feature, ✅ Test

#55 [Feat] OAuth 환경변수를 설정한다
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: 🌏 Deploy

#59 [Feat] S3를 필요한 API와 연결한다
  src/main/java/com/example/cargive/domain/car/controller/CarController.java
  src/main/java/com/example/cargive/domain/car/service/CarService.java
  src/main/java/com/example/cargive/domain/member/controller/MemberController.java
  src/main/java/com/example/cargive/domain/member/service/MemberService.java
  src/test/java/com/example/cargive/car/service/CarServiceTest.java
  src/test/java/com/example/cargive/member/service/MemberServiceTest.java
Labels: ✨ Feature

#64 [Docs] API 명세서 템플릿을 작성한다
  src/test/java/com/example/cargive/answer/controller/AnswerControllerTest.java
  src/test/java/com/example/cargive/car/controller/CarControllerTest.java
  src/test/java/com/example/cargive/common/ApiDocumentUtils.java
  src/test/java/com/example/cargive/favorite/controller/FavoriteCarControllerTest.java
  src/test/java/com/example/cargive/favorite/controller/FavoritePkGroupControllerTest.java
  src/test/java/com/example/cargive/favorite/controller/FavoritePkInfoControllerTest.java
  src/test/java/com/example/cargive/history/controller/HistoryControllerTest.java
  src/test/java/com/example/cargive/member/controller/MemberControllerTest.java
  src/test/java/com/example/cargive/notice/controller/NoticeControllerTest.java
  src/test/java/com/example/cargive/parkinglot/controller/ParkingLotControllerTest.java
  src/test/java/com/example/cargive/question/controller/QuestionControllerTest.java
  src/test/java/com/example/cargive/question/controller/QuestionFindControllerTest.java
  src/test/java/com/example/cargive/tag/controller/TagControllerTest.java
Labels: 📃 Docs

#65 [Docs] API 명세서를 작성한다
  src/docs/asciidoc/answer.adoc
  src/docs/asciidoc/car.adoc
  src/docs/asciidoc/favoriteCar.adoc
  src/docs/asciidoc/favoritePkGroup.adoc
  src/docs/asciidoc/favoritePkInfo.adoc
  src/docs/asciidoc/history.adoc
  src/docs/asciidoc/member.adoc
  src/docs/asciidoc/notice.adoc
  src/docs/asciidoc/parkingLot.adoc
  src/docs/asciidoc/tag.adoc
  src/main/java/com/example/cargive/domain/member/controller/MemberController.java
  src/main/java/com/example/cargive/domain/notice/controller/NoticeController.java
  src/test/java/com/example/cargive/answer/controller/AnswerControllerTest.java
  src/test/java/com/example/cargive/car/controller/CarControllerTest.java
  src/test/java/com/example/cargive/favorite/controller/FavoriteCarControllerTest.java
  src/test/java/com/example/cargive/favorite/controller/FavoritePkGroupControllerTest.java
  src/test/java/com/example/cargive/favorite/controller/FavoritePkInfoControllerTest.java
  src/test/java/com/example/cargive/history/controller/HistoryControllerTest.java
  src/test/java/com/example/cargive/member/controller/MemberControllerTest.java
  src/test/java/com/example/cargive/notice/controller/NoticeControllerTest.java
  src/test/java/com/example/cargive/parkinglot/controller/ParkingLotControllerTest.java
  src/test/java/com/example/cargive/tag/controller/TagControllerTest.java
Labels: 📃 Docs

#67 [Fix] 머지 이후 오류를 수정한다
  src/test/java/com/example/cargive/answer/controller/AnswerControllerTest.java
  src/test/java/com/example/cargive/car/controller/CarControllerTest.java
  src/test/java/com/example/cargive/favorite/controller/FavoriteCarControllerTest.java
  src/test/java/com/example/cargive/favorite/controller/FavoritePkGroupControllerTest.java
  src/test/java/com/example/cargive/favorite/controller/FavoritePkInfoControllerTest.java
  src/test/java/com/example/cargive/history/controller/HistoryControllerTest.java
  src/test/java/com/example/cargive/member/controller/MemberControllerTest.java
  src/test/java/com/example/cargive/notice/controller/NoticeControllerTest.java
  src/test/java/com/example/cargive/parkinglot/controller/ParkingLotControllerTest.java
  src/test/java/com/example/cargive/question/controller/QuestionControllerTest.java
  src/test/java/com/example/cargive/question/controller/QuestionFindControllerTest.java
  src/test/java/com/example/cargive/tag/controller/TagControllerTest.java
Labels: 🐞 BugFix

#71 [Fix] 머지 이후 오류를 해결한다
  src/test/resources/application.yml
Labels: 🐞 BugFix
