Repository Car-Give/Backend, pull requests merged in 2023-09, with the labels that each got.

#5 [Docs] Issue 및 PR Template을 등록한다
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/error-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/refactor-report.md
  .github/ISSUE_TEMPLATE/setting-report.md
  .github/PULL_REQUEST_TEMPLATE.md
  build.gradle
  src/main/java/com/example/cargive/domain/Favorites/controller/FavoriteController.java
  src/main/java/com/example/cargive/domain/Favorites/dto/mapper/FavoriteMapper.java
  src/main/java/com/example/cargive/domain/Favorites/dto/request/FavoriteCreateRequest.java
  src/main/java/com/example/cargive/domain/Favorites/entity/Favorite.java
  src/main/java/com/example/cargive/domain/Favorites/exception/FavoriteNotFoundException.java
  src/main/java/com/example/cargive/domain/Favorites/repository/FavoritesRepository.java
  src/main/java/com/example/cargive/domain/Favorites/service/FavoriteService.java
  src/main/java/com/example/cargive/domain/ParkingLot/controller/ParkingLotController.java
  src/main/java/com/example/cargive/domain/ParkingLot/dto/mapper/ParkingLotMapper.java
  src/main/java/com/example/cargive/domain/ParkingLot/dto/request/ParkingLotCreateRequest.java
  src/main/java/com/example/cargive/domain/ParkingLot/dto/response/ParkingLotInfo.java
  src/main/java/com/example/cargive/domain/ParkingLot/dto/response/ParkingLotSliceInfo.java
  src/main/java/com/example/cargive/domain/ParkingLot/entity/ParkingLot.java
  src/main/java/com/example/cargive/domain/ParkingLot/exception/ParkingLotNotFoundException.java
  src/main/java/com/example/cargive/domain/ParkingLot/repository/ParkingLotRepository.java
  src/main/java/com/example/cargive/domain/ParkingLot/service/ParkingLotService.java
  src/main/java/com/example/cargive/global/config/JpaAuditingConfig.java
  src/main/java/com/example/cargive/global/domain/BaseEntity.java
  src/main/java/com/example/cargive/global/error/ErrorCode.java
  src/main/java/com/example/cargive/global/exception/BusinessException.java
  src/main/java/com/example/cargive/global/result/ResultCode.java
  src/main/java/com/example/cargive/global/result/ResultResponse.java
Labels: 📃 Docs

#13 [Feat] 문의 및 답변 Entity를 생성한다
  src/main/java/com/example/cargive/domain/answer/entity/Answer.java
  src/main/java/com/example/cargive/domain/question/entity/Category.java
  src/main/java/com/example/cargive/domain/question/entity/Question.java
Labels: ✨ Feature

#18 [Docs] PR Reviewer를 자동 설정한다
  .github/CODEOWNERS
Labels: 📃 Docs

#21 [Feat] BaseResponse와 BaseException에서 누락 및 오류를 수정한다
  src/main/java/com/example/cargive/global/base/BaseException.java
  src/main/java/com/example/cargive/global/base/BaseResponse.java
Labels: ✨ Feature

#19 [Feat] 주차장 즐겨찾기 등록, 수정, 삭제, 조회 API를 구현하고 주차장 API를 수정한다
  .gitignore
  build.gradle
  src/main/java/com/example/cargive/domain/favorite/controller/FavoriteController.java
  src/main/java/com/example/cargive/domain/favorite/controller/FavoritePkGroupController.java
  src/main/java/com/example/cargive/domain/favorite/controller/FavoritePkInfoController.java
  src/main/java/com/example/cargive/domain/favorite/controller/dto/request/FavoriteGroupEditRequest.java
  src/main/java/com/example/cargive/domain/favorite/controller/dto/request/FavoriteGroupRequest.java
  src/main/java/com/example/cargive/domain/favorite/controller/dto/response/FavoritePkGroupResponse.java
  src/main/java/com/example/cargive/domain/favorite/controller/dto/response/FavoritePkInfoResponse.java
  src/main/java/com/example/cargive/domain/favorite/dto/mapper/FavoriteMapper.java
  src/main/java/com/example/cargive/domain/favorite/dto/request/FavoriteCreateRequest.java
  src/main/java/com/example/cargive/domain/favorite/entity/Favorite.java
  src/main/java/com/example/cargive/domain/favorite/entity/FavoritePkGroup.java
  src/main/java/com/example/cargive/domain/favorite/entity/FavoritePkInfo.java
  src/main/java/com/example/cargive/domain/favorite/entity/repository/FavoritePkInfoRepository.java
  src/main/java/com/example/cargive/domain/favorite/entity/repository/FavoriteRepository.java
  src/main/java/com/example/cargive/domain/favorite/entity/sortCondition/FavoriteGroupSortCondition.java
  src/main/java/com/example/cargive/domain/favorite/entity/sortCondition/FavoriteInfoSortCondition.java
  src/main/java/com/example/cargive/domain/favorite/exception/FavoriteErrorStatus.java
  src/main/java/com/example/cargive/domain/favorite/exception/FavoriteNotFoundException.java
  src/main/java/com/example/cargive/domain/favorite/infra/query/FavoriteGroupQueryRepository.java
  src/main/java/com/example/cargive/domain/favorite/infra/query/FavoriteGroupQueryRepositoryImpl.java
  src/main/java/com/example/cargive/domain/favorite/infra/query/FavoriteInfoQueryRepository.java
  src/main/java/com/example/cargive/domain/favorite/infra/query/FavoriteInfoQueryRepositoryImpl.java
  src/main/java/com/example/cargive/domain/favorite/infra/query/dto/FavoriteQueryResponse.java
  src/main/java/com/example/cargive/domain/favorite/repository/FavoritesRepository.java
  src/main/java/com/example/cargive/domain/favorite/service/FavoritePkGroupFindService.java
  src/main/java/com/example/cargive/domain/favorite/service/FavoritePkGroupService.java
  src/main/java/com/example/cargive/domain/favorite/service/FavoritePkInfoService.java
  src/main/java/com/example/cargive/domain/favorite/service/FavoriteService.java
  src/main/java/com/example/cargive/domain/parkingLot/controller/ParkingLotController.java
  src/main/java/com/example/cargive/domain/parkingLot/controller/dto/request/ParkingLotRequest.java
  src/main/java/com/example/cargive/domain/parkingLot/controller/dto/response/ParkingLotResponse.java
  src/main/java/com/example/cargive/domain/parkingLot/dto/mapper/ParkingLotMapper.java
  src/main/java/com/example/cargive/domain/parkingLot/dto/request/ParkingLotCreateRequest.java
  src/main/java/com/example/cargive/domain/parkingLot/dto/response/ParkingLotInfo.java
  src/main/java/com/example/cargive/domain/parkingLot/dto/response/ParkingLotSliceInfo.java
  src/main/java/com/example/cargive/domain/parkingLot/entity/ParkingLot.java
  src/main/java/com/example/cargive/domain/parkingLot/entity/ParkingLotRepository.java
  src/main/java/com/example/cargive/domain/parkingLot/exception/ParkingLotErrorStatus.java
  src/main/java/com/example/cargive/domain/parkingLot/exception/ParkingLotNotFoundException.java
  src/main/java/com/example/cargive/domain/parkingLot/repository/ParkingLotRepository.java
  src/main/java/com/example/cargive/domain/parkingLot/service/ParkingLotFindService.java
  src/main/java/com/example/cargive/domain/parkingLot/service/ParkingLotService.java
Labels: 📬 API, ✨ Feature, 🔨 Refactor

#23 [Feat] 내 문의글 등록 및 삭제, 조회 API를 구현한다
  src/docs/asciidoc/question-find.adoc
  src/docs/asciidoc/question.adoc
  src/main/java/com/example/cargive/domain/member/entity/Email.java
  src/main/java/com/example/cargive/domain/member/exception/MemberErrorStatus.java
  src/main/java/com/example/cargive/domain/member/repository/MemberRepository.java
  src/main/java/com/example/cargive/domain/question/controller/QuestionController.java
  src/main/java/com/example/cargive/domain/question/controller/QuestionFindController.java
  src/main/java/com/example/cargive/domain/question/controller/dto/request/SaveQuestionRequest.java
  src/main/java/com/example/cargive/domain/question/controller/dto/response/LoadQuestionResponse.java
  src/main/java/com/example/cargive/domain/question/entity/Category.java
  src/main/java/com/example/cargive/domain/question/entity/repository/QuestionRepository.java
  src/main/java/com/example/cargive/domain/question/service/QuestionFindService.java
  src/main/java/com/example/cargive/domain/question/service/QuestionService.java
  src/main/java/com/example/cargive/global/base/BaseException.java
  src/main/java/com/example/cargive/global/base/BaseExceptionHandler.java
  src/main/java/com/example/cargive/global/base/BaseResponse.java
  src/main/java/com/example/cargive/global/base/BaseResponseStatus.java
  src/test/java/com/example/cargive/common/ControllerTest.java
  src/test/java/com/example/cargive/common/ServiceTest.java
  src/test/java/com/example/cargive/question/controller/QuestionControllerTest.java
  src/test/java/com/example/cargive/question/controller/QuestionFindControllerTest.java
  src/test/java/com/example/cargive/question/fixture/QuestionFixture.java
  src/test/java/com/example/cargive/question/service/QuestionFindServiceTest.java
  src/test/java/com/example/cargive/question/service/QuestionServiceTest.java
Labels: 📬 API, 📃 Docs, ✨ Feature, ✅ Test

#25 [Feat] 내 문의글 리스트 조회 API를 구현한다
  build.gradle
  src/docs/asciidoc/question-find.adoc
  src/main/java/com/example/cargive/domain/favorite/controller/FavoritePkGroupController.java
  src/main/java/com/example/cargive/domain/favorite/controller/FavoritePkInfoController.java
  src/main/java/com/example/cargive/domain/favorite/entity/sortCondition/FavoriteGroupSortCondition.java
  src/main/java/com/example/cargive/domain/favorite/entity/sortCondition/FavoriteInfoSortCondition.java
  src/main/java/com/example/cargive/domain/parkingLot/controller/ParkingLotController.java
  src/main/java/com/example/cargive/domain/question/controller/QuestionFindController.java
  src/main/java/com/example/cargive/domain/question/entity/repository/QuestionRepository.java
  src/main/java/com/example/cargive/domain/question/infra/query/QuestionFindQueryRepository.java
  src/main/java/com/example/cargive/domain/question/infra/query/QuestionFindQueryRepositoryImpl.java
  src/main/java/com/example/cargive/domain/question/service/QuestionFindService.java
  src/main/java/com/example/cargive/domain/question/service/response/GetListOfQuestionResponse.java
  src/main/java/com/example/cargive/domain/question/service/response/LoadQuestionResponse.java
  src/main/java/com/example/cargive/global/base/BaseResponseStatus.java
  src/test/java/com/example/cargive/member/fixture/MemberFixture.java
  src/test/java/com/example/cargive/question/controller/QuestionFindControllerTest.java
  src/test/java/com/example/cargive/question/fixture/QuestionFixture.java
  src/test/java/com/example/cargive/question/infra/query/QuestionFindQueryRepositoryImplTest.java
Labels: 📬 API, 📃 Docs, ✨ Feature, ✅ Test

#28 [Fix] 머지 후 충돌을 해결한다
  src/test/java/com/example/cargive/car/service/CarServiceTest.java
  src/test/java/com/example/cargive/favorite/domain/FavoriteInfoTest.java
  src/test/java/com/example/cargive/favorite/domain/favorite/FavoriteCarTest.java
  src/test/java/com/example/cargive/favorite/domain/favorite/FavoritePkGroupTest.java
  src/test/java/com/example/cargive/favorite/service/FavoriteCarServiceTest.java
  src/test/java/com/example/cargive/favorite/service/FavoritePkGroupServiceTest.java
  src/test/java/com/example/cargive/favorite/service/FavoritePkInfoServiceTest.java
  src/test/java/com/example/cargive/member/fixture/MemberFixture.java
Labels: 🐞 BugFix
